# Generated by Django 4.2.5 on 2023-09-07 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsbackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapedarticle',
            name='author',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='canonical_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='copyright',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='depth',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='lang',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='links',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='loaded_domain',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='loaded_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='publisher',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='referrer',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='soft_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='start_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='tags',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scrapedarticle',
            name='videos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
