# Generated by Django 4.2.5 on 2023-09-09 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsbackend', '0002_alter_scrapedarticle_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedarticle',
            name='generated_image',
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
